"""Programmatic real-SDL smoke checks and actual frozen frame captures.

The drag coordinates are injected into the host, not generated by an OS mouse
robot. This script deliberately reports that distinction. Use after build.py.
"""
from __future__ import annotations
import argparse
import asyncio
import hashlib
import json
import os
from pathlib import Path
import platform
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
os.environ.setdefault("PYGAME_HIDE_SUPPORT_PROMPT", "1")


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


async def wait_until(predicate, timeout=5):
    from time import monotonic
    until = monotonic() + timeout
    while not predicate():
        if monotonic() >= until:
            raise TimeoutError("Native verification fixture did not become ready")
        await asyncio.sleep(.02)


async def source_host(output):
    import pygame
    from arrow_y2k.app import ArrowApp
    from arrow_y2k.desktop import PixelHost
    from arrow_y2k.windowing import choose_work_area, place_window
    from textual.widgets import Button

    with tempfile.TemporaryDirectory(prefix="native-host-", dir=ROOT / ".artifacts") as data:
        app = ArrowApp(seed="native-window-check", data_dir=data)
        host = PixelHost(app)
        task = asyncio.create_task(host.run(quit_after=20))
        record = {}
        try:
            await wait_until(lambda: app._page_ready and host._window is not None)
            if pygame.display.get_driver() == "dummy":
                raise RuntimeError("This verification requires a real SDL display")
            geometry = host.geometry
            areas = geometry.work_areas()
            record["driver"] = pygame.display.get_driver()
            record["work_areas"] = [area.__dict__ for area in areas]
            record["native_global_pointer_available"] = geometry.global_pointer() is not None
            original = tuple(host._window.position)
            area = choose_work_area(areas, (*original, 1280, 720))
            record["startup_position"] = original
            assert original == place_window((1280, 720), area)

            # An actual SDL window moves, but pointer samples come from a
            # deterministic fixture. Preserve the real capture/work-area APIs.
            class InjectedPointer:
                def __init__(self):
                    self.pointer = (original[0] + 980, original[1] + 10)
                def global_pointer(self):
                    return self.pointer
                def capture_pointer(self, enabled):
                    geometry.capture_pointer(enabled)
                def work_areas(self):
                    return geometry.work_areas()
            injected = InjectedPointer()
            host._geometry = injected
            host.process_event(pygame.event.Event(pygame.MOUSEBUTTONDOWN, button=1, pos=(980, 10)))
            assert host._drag is not None
            injected.pointer = (injected.pointer[0] + 90, injected.pointer[1] + 65)
            host.process_event(pygame.event.Event(pygame.MOUSEMOTION, pos=(1070, 75), rel=(90, 65), buttons=(1, 0, 0)))
            moved = tuple(host._window.position)
            assert moved == (original[0] + 90, original[1] + 65)
            host.process_event(pygame.event.Event(pygame.MOUSEMOTION, pos=(980, 10), rel=(0, 0), buttons=(1, 0, 0)))
            assert tuple(host._window.position) == moved
            host.process_event(pygame.event.Event(pygame.MOUSEBUTTONUP, button=1, pos=(980, 10)))
            host._geometry = geometry
            record["programmatic_drag"] = {"before": original, "after": moved, "local_coordinate_jitter": False}

            resize = []
            for name in ("1920x1080", "1024x768", "1280x720"):
                old_position = tuple(host._window.position)
                selected = choose_work_area(areas, (*old_position, host.resolution.width, host.resolution.height))
                host.handle_action("resolution:" + name)
                await asyncio.sleep(.1)
                size = (host.resolution.width, host.resolution.height)
                position = tuple(host._window.position)
                assert position == place_window(size, selected, old_position)
                assert tuple(pygame.display.get_window_size()) == size
                resize.append({"resolution": name, "position": position, "size": size})
            record["native_resizes"] = resize

            with app._context():
                app.action_menu()
            await wait_until(lambda: app.page == "menu" and app._page_ready)
            button = app.screen.query_one("#minimize", Button)
            app._set_mouse_over(button, button)
            button.add_class("-active")
            button.focus()
            host.handle_action("minimize")
            await asyncio.sleep(.15)
            assert app.mouse_over is None and app.hover_over is None
            assert not button.has_class("-active") and not button.has_focus
            host._window.restore()
            await asyncio.sleep(.2)
            assert app.mouse_over is None and app.hover_over is None
            assert not button.has_class("-active") and not button.has_focus
            record["minimize_restore_clears_transient_state"] = True
            record["scope"] = "Real SDL windows and positions; injected host drag coordinates; direct native minimize/restore; no manual or OS mouse drag replay"
        finally:
            host._request_exit()
            await task
        return record


def binary_frames(output, executable):
    from PIL import Image
    from arrow_y2k.desktop import RESOLUTIONS
    records = []
    for name, resolution in RESOLUTIONS.items():
        screenshot = output / f"{name}.png"
        with tempfile.TemporaryDirectory(prefix="native-exe-", dir=ROOT / ".artifacts") as data:
            args = [str(executable), "--resolution", name, "--data-dir", data,
                    "--screenshot", str(screenshot), "--quit-after", "1.3"]
            process = subprocess.run(args, cwd=ROOT, timeout=30, check=True)
            log = Path(data, "runtime.log")
            log_text = log.read_text(encoding="utf-8") if log.exists() else ""
            assert "Traceback" not in log_text
        frame = Image.open(screenshot).convert("RGB")
        assert frame.size == (resolution.width, resolution.height)
        reduced = frame.resize(resolution.logical_size, Image.Resampling.NEAREST)
        assert reduced.resize(frame.size, Image.Resampling.NEAREST).tobytes() == frame.tobytes()
        records.append({"resolution": name, "size": frame.size, "scale": resolution.scale,
                        "exit_code": process.returncode, "screenshot": screenshot.name,
                        "sha256": sha256(screenshot), "runtime_log": log_text})
    return records


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "output" / "native-v3")
    parser.add_argument("--source-only", action="store_true")
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    (ROOT / ".artifacts").mkdir(exist_ok=True)
    if os.environ.get("SDL_VIDEODRIVER") == "dummy":
        raise RuntimeError("Unset SDL_VIDEODRIVER=dummy for real-window verification")
    report = {"platform": platform.platform(), "source_native": asyncio.run(source_host(args.output))}
    if not args.source_only:
        executable = ROOT / "dist" / "A.A.A-Y2K" / "A.A.A-Y2K.exe"
        report["executable_sha256"] = sha256(executable)
        report["frozen_frames"] = binary_frames(args.output, executable)
    path = args.output / "report.json"
    path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
